/***
firebase_options.dart: Firebase Options module
created by @lanri.jait@gmail.com
last committed by @
***/

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCqWMXsRI7i0RIndRrCdz8S9g6wTYSFz8',
    appId: '1:766566884354:web:6957862572674488a9331b',
    messagingSenderId: '766566884354',
    projectId: 'tiara-mode-project',
    authDomain: 'tiara-mode-project.firebaseapp.com',
    storageBucket: 'tiara-mode-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd3PCkOM7yGS2lASma7F-Gqy7aaCZLsvA',
    appId: '1:766566884354:android:1c6223c8b6d408aca9331b',
    messagingSenderId: '766566884354',
    projectId: 'tiara-mode-project',
    storageBucket: 'tiara-mode-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjgIcDcS_tPtT1oXgBZYR7uWysWi-nKB0',
    appId: '1:766566884354:ios:7aa105af75e2ecdda9331b',
    messagingSenderId: '766566884354',
    projectId: 'tiara-mode-project',
    storageBucket: 'tiara-mode-project.firebasestorage.app',
    iosClientId: '766566884354-mqcdubdu2l4vr11ila9eij2f3nfu4e15.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiaraMode',
  );

}